name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
       pwd
       ls -a
       echo ${{ secrets.USER }} ${{ secrets.PWD }} 
       echo ${{ secrets.Docker_Hub.USER }} ${{ secrets.Docker_Hub.PWD }}
       docker build . --file Dockerfile --tag my-image-name:v1
    - name: Login to Docker Hub 
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.Docker_Hub.USER }}
          password: ${{ secrets.Docker_Hub.PWD }}
    - name: Push the Docker image
      run: |
       docker push my-image-name:v1
