name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
       pwd
       ls -a
       docker build . --file Dockerfile --tag my-image-name:v1
       docker push my-image-name:v1
